// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WaterPing is the golang structure of table water_ping for DAO operations like Where/Data.
type WaterPing struct {
	g.Meta    `orm:"table:water_ping, dto:true"`
	WaterFrom interface{} //
	WaterTo   interface{} //
	Delay     interface{} //
}
