// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Water is the golang structure for table water.
type Water struct {
	WaterId       string      `json:"waterId"       description:""`
	VerifySession string      `json:"verifySession" description:""`
	Key           string      `json:"key"           description:""`
	Url           string      `json:"url"           description:""`
	IsBanned      bool        `json:"isBanned"      description:""`
	IsVerified    bool        `json:"isVerified"    description:""`
	IsReviewed    bool        `json:"isReviewed"    description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
	IsSelf        bool        `json:"isSelf"        description:""`
}

// WaterPing is the golang structure for table water_ping.
type WaterPing struct {
	WaterFrom string `json:"waterFrom" description:""`
	WaterTo   string `json:"waterTo"   description:""`
	Delay     int64  `json:"delay"     description:""`
}

// WaterRoute is the golang structure for table water_route.
type WaterRoute struct {
	WaterTo  string `json:"waterTo"  description:""`
	Route    string `json:"route"    description:""`
	Delay    int64  `json:"delay"    description:""`
	Disabled bool   `json:"disabled" description:""`
	Skipped  bool   `json:"skipped"  description:""`
}
