// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sea/internal/service/internal/dao/internal"
)

// waterTrustDao is the data access object for table water_trust.
// You can define custom methods on it to extend its functionality as you wish.
type waterTrustDao struct {
	*internal.WaterTrustDao
}

var (
	// WaterTrust is globally public accessible object for table water_trust operations.
	WaterTrust = waterTrustDao{
		internal.NewWaterTrustDao(),
	}
)

// Fill with you ideas below.
