// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sea/internal/service/internal/dao/internal"
)

// waterSessionDao is the data access object for table water_session.
// You can define custom methods on it to extend its functionality as you wish.
type waterSessionDao struct {
	*internal.WaterSessionDao
}

var (
	// WaterSession is globally public accessible object for table water_session operations.
	WaterSession = waterSessionDao{
		internal.NewWaterSessionDao(),
	}
)

// Fill with you ideas below.
