// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sea/app/dao/internal"
)

// seaDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type seaDao struct {
	*internal.SeaDao
}

var (
	// Sea is globally public accessible object for table sea operations.
	Sea = seaDao{
		internal.NewSeaDao(),
	}
)

// Fill with you ideas below.
