// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sea/app/dao/internal"
)

// waterPingDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type waterPingDao struct {
	*internal.WaterPingDao
}

var (
	// WaterPing is globally public accessible object for table water_ping operations.
	WaterPing = waterPingDao{
		internal.NewWaterPingDao(),
	}
)

// Fill with you ideas below.
