// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"sea/app/dao/internal"
)

// waterUrlDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type waterUrlDao struct {
	*internal.WaterUrlDao
}

var (
	// WaterUrl is globally public accessible object for table water_url operations.
	WaterUrl = waterUrlDao{
		internal.NewWaterUrlDao(),
	}
)

// Fill with you ideas below.
