// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TransferQueue is the golang structure of table transfer_queue for DAO operations like Where/Data.
type TransferQueue struct {
	g.Meta           `orm:"table:transfer_queue, do:true"`
	TransferId       interface{} //
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
	TransactionId    interface{} //
	TransactionOrder interface{} //
	Origin           interface{} //
	Target           interface{} //
	From             interface{} //
	To               interface{} //
	MessageType      interface{} //
	MessageJson      interface{} //
}
