// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 16:37:39
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WaterSession is the golang structure of table water_session for DAO operations like Where/Data.
type WaterSession struct {
	g.Meta      `orm:"table:water_session, do:true"`
	Id          interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	SessionId   interface{} //
	SessionType interface{} //
	SessionKey  interface{} // 32 bytes of key + 16 bytes of iv
}
