// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WaterPing is the golang structure of table water_ping for DAO operations like Where/Data.
type WaterPing struct {
	g.Meta    `orm:"table:water_ping, do:true"`
	WaterFrom interface{} //
	WaterTo   interface{} //
	Delay     interface{} //
}
