// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TransferQueue is the golang structure for table transfer_queue.
type TransferQueue struct {
	TransferId       string      `json:"transferId"       description:""`
	CreatedAt        *gtime.Time `json:"createdAt"        description:""`
	UpdatedAt        *gtime.Time `json:"updatedAt"        description:""`
	TransactionId    string      `json:"transactionId"    description:""`
	TransactionOrder int64       `json:"transactionOrder" description:""`
	Origin           string      `json:"origin"           description:""`
	Target           string      `json:"target"           description:""`
	From             string      `json:"from"             description:""`
	To               string      `json:"to"               description:""`
	MessageType      int64       `json:"messageType"      description:""`
	MessageJson      string      `json:"messageJson"      description:""`
}
