// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 16:37:39
// =================================================================================

package entity

// Users is the golang structure for table users.
type Users struct {
	Id       string `json:"id"       description:""`
	Username string `json:"username" description:""`
	Password string `json:"password" description:""`
}
