// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 16:37:39
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WaterSession is the golang structure for table water_session.
type WaterSession struct {
	Id          int64       `json:"id"          description:""`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
	SessionId   string      `json:"sessionId"   description:""`
	SessionType int         `json:"sessionType" description:""`
	SessionKey  string      `json:"sessionKey"  description:"32 bytes of key + 16 bytes of iv"`
}
