// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// =================================================================================

package entity

// WaterRoute is the golang structure for table water_route.
type WaterRoute struct {
	WaterTo  string `json:"waterTo"  description:""`
	Route    string `json:"route"    description:""`
	Delay    int64  `json:"delay"    description:""`
	Disabled bool   `json:"disabled" description:""`
	Skipped  bool   `json:"skipped"  description:""`
}
