// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WaterPing is the golang structure for table water_ping.
type WaterPing struct {
	WaterFrom string `json:"waterFrom" ` //
	WaterTo   string `json:"waterTo"   ` //
	Delay     int64  `json:"delay"     ` //
}
