// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// WaterRoute is the golang structure for table water_route.
type WaterRoute struct {
	WaterTo  string `json:"waterTo"  ` //
	Route    string `json:"route"    ` //
	Delay    int64  `json:"delay"    ` //
	Disabled bool   `json:"disabled" ` //
	Skipped  bool   `json:"skipped"  ` //
}
