// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Water is the golang structure for table water.
type Water struct {
	WaterId       string      `json:"waterId"       ` //
	VerifySession string      `json:"verifySession" ` //
	Key           string      `json:"key"           ` //
	Url           string      `json:"url"           ` //
	IsBanned      bool        `json:"isBanned"      ` //
	IsVerified    bool        `json:"isVerified"    ` //
	IsReviewed    bool        `json:"isReviewed"    ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
	IsSelf        bool        `json:"isSelf"        ` //
}
