// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Water is the golang structure for table water.
type Water struct {
	WaterId       string      `json:"waterId"       description:""`
	VerifySession string      `json:"verifySession" description:""`
	Key           string      `json:"key"           description:""`
	Url           string      `json:"url"           description:""`
	IsBanned      bool        `json:"isBanned"      description:""`
	IsVerified    bool        `json:"isVerified"    description:""`
	IsReviewed    bool        `json:"isReviewed"    description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
	IsSelf        bool        `json:"isSelf"        description:""`
}
