// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:29:21
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WaterPingDao is the data access object for table water_ping.
type WaterPingDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns WaterPingColumns // columns contains all the column names of Table for convenient usage.
}

// WaterPingColumns defines and stores column names for table water_ping.
type WaterPingColumns struct {
	WaterFrom string //
	WaterTo   string //
	Delay     string //
}

//  waterPingColumns holds the columns for table water_ping.
var waterPingColumns = WaterPingColumns{
	WaterFrom: "water_from",
	WaterTo:   "water_to",
	Delay:     "delay",
}

// NewWaterPingDao creates and returns a new DAO object for table data access.
func NewWaterPingDao() *WaterPingDao {
	return &WaterPingDao{
		group:   "default",
		table:   "water_ping",
		columns: waterPingColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WaterPingDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WaterPingDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WaterPingDao) Columns() WaterPingColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WaterPingDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WaterPingDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WaterPingDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
