// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// WaterInviteDao is the manager for logic model data accessing and custom defined data operations functions management.
type WaterInviteDao struct {
	Table   string             // Table is the underlying table name of the DAO.
	Group   string             // Group is the database configuration group name of current DAO.
	Columns WaterInviteColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// WaterInviteColumns defines and stores column names for table water_invite.
type WaterInviteColumns struct {
	InviteCode  string //
	BindWaterId string //
	CreatedAt   string //
}

//  waterInviteColumns holds the columns for table water_invite.
var waterInviteColumns = WaterInviteColumns{
	InviteCode:  "invite_code",
	BindWaterId: "bind_water_id",
	CreatedAt:   "created_at",
}

// NewWaterInviteDao creates and returns a new DAO object for table data access.
func NewWaterInviteDao() *WaterInviteDao {
	return &WaterInviteDao{
		Group:   "default",
		Table:   "water_invite",
		Columns: waterInviteColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WaterInviteDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WaterInviteDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WaterInviteDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
